import Services from "@/components/home/Services";

export const metadata = {
  title: "All Services",
  description: "Generated by create next app",
};

export default function ServicesPage() {
  return (
    <div>
      <Services />
    </div>
  );
}
